### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by LeakPro** [Jackbail4/Black-ops-2-Plutonium-Cheat#1]
was this in working condition ?

i build the dll but after injecting nothing happens

**Comment by b1gnout** [comment]
Hello, I've just tested it and it is still working for me. Try entering a bot lobby, then inject. 

![Untitled](https://user-images.githubusercontent.com/64487175/153357824-53fcbb2a-7632-434b-9928-c1b369a020c2.png)
